spring.application.name=workflows
management.otlp.metrics.export.url=https://ingress.europe-west4.gcp.dash0.com/v1/metrics
management.otlp.metrics.export.headers.Authorization=${OTEL_AUTH_TOKEN}
management.otlp.metrics.export.headers.Content-Type=application/json
management.otlp.metrics.export.headers.Dash0-Dataset=default
management.opentelemetry.tracing.export.otlp.endpoint=https://ingress.europe-west4.gcp.dash0.com/v1/traces
management.opentelemetry.tracing.export.otlp.headers.Authorization=${OTEL_AUTH_TOKEN}
management.opentelemetry.tracing.export.otlp.headers.Dash0-Dataset=default
management.opentelemetry.tracing.export.otlp.headers.Content-Type=application/json
management.opentelemetry.logging.export.otlp.endpoint=https://ingress.europe-west4.gcp.dash0.com/v1/logs
management.opentelemetry.logging.export.otlp.headers.Authorization=${OTEL_AUTH_TOKEN}
management.opentelemetry.logging.export.otlp.headers.Dash0-Dataset=default
management.opentelemetry.logging.export.otlp.headers.Content-Type=application/json

